### PR TITLE
Proposal of refactorization

### PR DESCRIPTION
**Pull request by ghost**
@antonbabenko I think this kind of refactor will allow us to add separation between `cidr` and is much more readable. Write me your feedback about that, please.

### CODE REVIEW

**Comment by kamilboratynski** [comment]
@antonbabenko I think this kind of refactor will allow us to add separation between `cidr` and is much more readable. Write me your feedback about that, please.

**Comment by antonbabenko** [comment]
This looks like a good start! Now users of this module will be able to use output `security_group_id` and add custom rules.

PS: There is no need to wrap variables of type `list` with `[` and `]` as of Terraform 0.9.6. See [changelog](https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#096-may-25-2017).

**Comment by ghost** [comment]
@antonbabenko Updated.

**Comment by antonbabenko** [comment]
Lots of changes here. Looks good to me and I think we can merge it if you have tested some of the code yourself. Have you tested some of it? :)

**Comment by ghost** [comment]
@antonbabenko I did `terraform plan` for some modules, but more or less, it is good point to prepare some CI for modules. ;-)

**Comment by antonbabenko** [comment]
@kamilboratynski CI for modules is what I am working on in my spare time.

Merging now.

**Comment by antonbabenko** [comment]
Tagged as https://github.com/terraform-community-modules/tf_aws_sg/releases/tag/v0.2.2

**Pull request merged**
