### PR TITLE
Add TCP/UDP:8302(Serf WAN) to sg_consul

### PR DESCRIPTION
**Pull request by sioncojp**
This PR is able to communicate with consul-server to consul-server.
The reason is that in order to manage multi-dc.

ref: https://www.consul.io/docs/agent/options.html#ports-used

### CODE REVIEW

**Comment by antonbabenko** [comment]
@sioncojp Thanks for the code. This PR will have to be implemented as part of https://github.com/terraform-aws-modules/terraform-aws-security-group/issues/1 , because the current repository is going to be deprecated shortly. I will try to make it during today.

**Comment by sioncojp** [comment]
I get it.
I'm gonna send PR to [github.com/terraform-aws-modules/terraform-aws-security-group](https://github.com/terraform-aws-modules/terraform-aws-security-group) also when that repository will fix.
Or if you are give me LGTM to this idea, it's ok to implement like this.

**Comment by antonbabenko** [comment]
Merged now, and will implement it in the new place.

**Comment by sioncojp** [comment]
Thank you!!

**Pull request merged**
