### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by radeksimko**
Most of the examples simply don't work and end up with similar errors:

> Error loading Terraform: Error downloading modules: module sg_web: open .terraform/modules/f551cceae759ac94eb586588d1bd61ce/sg-web: no such file or directory

### CODE REVIEW

**Comment by solarce** [comment]
Is that output from trying to run `terraform get -update`? Can you provide an example and include how you're declaring your module resource?

**Comment by solarce** [comment]
These are not typos, if you review http://www.terraform.io/docs/modules/sources.html you'll see it specifically says

> Subdirectories within the repository can also be referenced:
> 
> module "consul" {
>    source = "github.com/hashicorp/example//subdir"
> }
> Note: The double-slash is important. It is what tells Terraform that that is the separator for a subdirectory, and not part of the repository itself.

**Comment by solarce** [comment]
I pushed https://github.com/solarce/tf_zookeeper and an example of testing it out is available at https://gist.github.com/solarce/b77110786e5dbd5dc2b9

**Comment by radeksimko** [comment]
I apologise for not providing a sample TF code, so here you go:

``` ruby
provider "aws" {
    access_key = "${var.aws_access_key}"
    secret_key = "${var.aws_secret_key}"
    region = "${var.aws_region}"
}

module "sg_web" {
  source = "github.com/terraform-community-modules/tf_aws_sg//sg-web"
  security_group_name = "bollocks-web"
  aws_access_key = "${var.aws_access_key}"
  aws_secret_key = "${var.aws_secret_key}"
  aws_region = "${var.aws_region}"
  vpc_id = "vpc-aaabbbc"
  source_cidr_block = "0.0.0.0/0"
}
```

1) The error comes from `terraform get`, but on further inspection it seems that terraform did clone the repository, but it's failing to link it somehow to the module in the code? Either way I don't know of any magic in Terraform that would convert **underscores** to **hyphens**. If there is such, then it firstly doesn't work and secondly it would be quite confusing.

2) Thanks for explaining the `//` (double slash). It does work for me with single slash though and it has exactly the same effect as double slash.
I tried both in the example above - `github.com/terraform-community-modules/tf_aws_sg//sg_web` and `github.com/terraform-community-modules/tf_aws_sg/sg_web`.

```
$ diff -r .terraform-single-slash .terraform-double-slash
```

```
Binary files .terraform/modules/f551cceae759ac94eb586588d1bd61ce/.git/index and .terraform-double-slash/modules/f551cceae759ac94eb586588d1bd61ce/.git/index differ
diff -r .terraform/modules/f551cceae759ac94eb586588d1bd61ce/.git/logs/HEAD .terraform-double-slash/modules/f551cceae759ac94eb586588d1bd61ce/.git/logs/HEAD
1c1
< 0000000000000000000000000000000000000000 b599071273cc3b35b9c55946f531ac732d577676 Radek Simko <radek.simko@gmail.com> 1426578823 +0000    clone: from https://github.com/terraform-community-modules/tf_aws_sg.git
---
> 0000000000000000000000000000000000000000 b599071273cc3b35b9c55946f531ac732d577676 Radek Simko <radek.simko@gmail.com> 1426578788 +0000    clone: from https://github.com/terraform-community-modules/tf_aws_sg.git
diff -r .terraform/modules/f551cceae759ac94eb586588d1bd61ce/.git/logs/refs/heads/master .terraform-double-slash/modules/f551cceae759ac94eb586588d1bd61ce/.git/logs/refs/heads/master
1c1
< 0000000000000000000000000000000000000000 b599071273cc3b35b9c55946f531ac732d577676 Radek Simko <radek.simko@gmail.com> 1426578823 +0000    clone: from https://github.com/terraform-community-modules/tf_aws_sg.git
---
> 0000000000000000000000000000000000000000 b599071273cc3b35b9c55946f531ac732d577676 Radek Simko <radek.simko@gmail.com> 1426578788 +0000    clone: from https://github.com/terraform-community-modules/tf_aws_sg.git
diff -r .terraform/modules/f551cceae759ac94eb586588d1bd61ce/.git/logs/refs/remotes/origin/HEAD .terraform-double-slash/modules/f551cceae759ac94eb586588d1bd61ce/.git/logs/refs/remotes/origin/HEAD
1c1
< 0000000000000000000000000000000000000000 b599071273cc3b35b9c55946f531ac732d577676 Radek Simko <radek.simko@gmail.com> 1426578823 +0000    clone: from https://github.com/terraform-community-modules/tf_aws_sg.git
---
> 0000000000000000000000000000000000000000 b599071273cc3b35b9c55946f531ac732d577676 Radek Simko <radek.simko@gmail.com> 1426578788 +0000    clone: from https://github.com/terraform-community-modules/tf_aws_sg.git
```

The only difference really is in timestamps = there's no difference.
More importantly the single slash works when running `terraform apply`:

```
module.sg_web.aws_security_group.main_security_group: Creation complete

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

I'm not saying the double slash does any harm (compared to the hyphens), it just seems superfluous to me.

---

It's usually more polite to give some time for answering the questions and clarifying the reasons instead of closing the issue without answer after few hours. I personally don't mind, but this could be quite demotivating for any new contributor.

**Comment by solarce** [comment]
I apologize, I jumped the gun on closing this PR and that was both rude and unnecessary. That's not the kind of experience I'd want or that I want to give others, so I am sorry for that. 

Sadly, I completely missed the hyphen to underscore changes, which I see now is in your commit message and the changes, I only noticed you removing the double slashes, since the official documentation tells us to use them, I want to keep them, but if you want to redo this PR with the underscore fix, I'd be happy to merge it, as that does need to be fixed.

**Comment by radeksimko** [comment]
> I want to keep them, but if you want to redo this PR with the underscore fix

Cool, I will update the PR.

**Comment by radeksimko** [comment]
PR updated.

**Comment by solarce** [comment]
Thank you for catching this and getting a fix for it quickly. Again, apologies for the abrupt behavior early and thank you for calling me out on it.

**Comment by radeksimko** [comment]
No worries, I'm noting down for myself to look at the implementation details on how does Terraform handle the double-slashes or generally to find out if there's actually any special functionality or it's just a rule mentioned in docs and DSL parser just ignores it.

**Comment by mitchellh** [comment]
I want to comment here. @solarce I'm impressed that you found the double slash. That is a RTFM that I never thought anyone would get, so much so in fact that I added "implicit double slashes" in at various points. For example, with GitHub we know after "github.com/user/repo" that it will ALWAYS be a double-slash there. So I do it.

But in some cases a double slash is _required_, namely file paths and HTTP URLs.

The more you know(tm).

**Pull request merged**
